[tmdb]
  api_key = ""

[[indexers]]
  name = "My Indexer"
  url = "http://indexer"
  api_key = ""
  categories = "2000,100002,100004,100001,100054,100042,100070,100055,100003,100076,2010,2020,2030,2040,2045,2050,2060,2070,2080"

[[qualities]]
  name = "720p"
  regex = "720"
  min_size = 5e8
  max_size = 1e10
  resolution = "1280x720"

[[qualities]]
  name = "1080p"
  regex = "1080"
  min_size = 5e8
  max_size = 1e10
  resolution = "1920x1080"

[transcoder]
  [transcoder.video]
    compression_algo = "libx264"
    format = "ismv"
  [transcoder.audio]
    compression_algo = "copy"


[torrent_client]
  min_seeders = 2
  info_timeout = 30
  file_path = "./downloads"
  data_path = "./downloads"
  established_conns_per_torrent = 15
  torrent_half_open_conns_per_torrent = 15
  meta_refresh_rate = 5
