[tmdb]
  api_key= ""

[torrent_fetcher]

  quality_score_expr = "quality * 0.35"

  [[torrent_fetcher.indexers]]
    name = "all"
    url = "http://localhost:9117/api/v2.0/indexers/all/results/torznab/"
    api_key = "<api-key>" 
    categories = "2000,100002,100004,100001,100054,100042,100070,100055,100003,100076,2010,2020,2030,2040,2045,2050,2060,2070,2080"

  [[torrent_fetcher.qualities]]
    name = "720p"
    regex = "720"
    min_size = 5e8
    max_size = 1e10
    min_seeders = 2
    resolution = "1280x720"
    # Function that approaches 1 as seed count goes up
    seeder_score_expr = "(-3 * 1/(seeders+3)) + 1"
    # Function that starts around 0, peaks at 8000 and then tapers off back to 0 saying the ideal is 8000
    size_score_expr = "10**7 * 1/((sizeMB - 8000)**2 + 10**7)"
    
  [[torrent_fetcher.qualities]]
    name = "1080p"
    regex = "1080"
    min_size = 5e8
    max_size = 1e10
    min_seeders = 2
    resolution = "1920x1080"
    # Function that approaches 1 as seed count goes up
    seeder_score_expr = "(-3 * 1/(seeders+3)) + 1"
    # Function that starts around 0, peaks at 12000 and then tapers off back to 0 saying the ideal is 12000
    size_score_expr = "10**7 * 1/((sizeMB - 12000)**2 + 10**7)"
    

[transcoder]
  [transcoder.video]
    compression_algo = "libx264"
    format = "ismv"
  [transcoder.audio]
    compression_algo = "libmp3lame"

[torrent_client]
  info_timeout = 30
  file_path = "./downloads"
  data_path = "./downloads"
  established_conns_per_torrent = 15
  torrent_half_open_conns_per_torrent = 15
  meta_refresh_rate = 5
