indexers:
    - name: TorrentLeech
      url: https://jackett.internal.url/api/v2.0/indexers/<indexer>/results/torznab/
      apiKey: <api-key> 
      categories:
          - 5000
          - 5020
          - 5030
          - 5040
          - 5070
          - 5070
          - 5080
          - 100027